# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DermaCare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DermaCare
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod ‘Firebase/Storage’
  pod 'SwiftyJSON'
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'
  target 'DermaCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DermaCareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
